use rand::seq::IndexedRandom;

pub fn get_random_exaclamatory() -> String {
    let mut rng = rand::rng();
    let sources = vec![
        "wowza",
        "cowabunga",
        "slamtastic",
        "bada bing",
        "call your mom",
    ];
    let chosen_word = *sources.choose(&mut rng).unwrap();
    chosen_word.to_string()
}

pub fn get_bird_description() -> String {
    let adjective = get_random_bird_adjective();
    format!("a {adjective} bird")
}

pub fn get_random_bird_adjective() -> String {
    let mut rng = rand::rng();
    let sources = vec![
        // make sure it can work with having "a" before it (no vowels first lol)
        // format will be
        // `a <string> bird`
        "kind and exemplary",
        "real smokin'",
        "street smart",
        "classic old school",
        "slam dunk",
        "wise and esteemed",
        "kinda gross",
        "poopy",
        "hot dog water kinda",
        "beer-battered",
        "melted cheese style",
        "respectful",
        "god-fearing",
        "truly sickening",
        "generally underrated",
        "sparkling water bird bath only",
        "slap yo mama",
        "'performative reading'",
        "kingly peasant",
        "swimmingly pleasant",
        "cheeseburger baby",
        "legally distinct",
        "tax evading",
        "dinky dunky doo",
        "bird, a sad bird, but still, a lovable",
        "government whistleblower",
        "pro-union (who isn't?)",
        "pseudo-anticapitalist?",
        "'school of hard knocks'-attending",
        "REAL",
        "FAKE",
        "smooth",
        "slimy little",
        "charming, but untrustworthy",
        "cop? uh oh geez hide the shi- oh no wait it's just a",
        "hyperpop-altjazz legend",
        "sexy fugitive",
        "dragon spirit gas engine",
        "matcha drinkin' <derogatory>",
        "mustard and mayo kinda",
        "potato bravas sorta",
        "felony-acquitted",
        "Dinker McDonker style",
        "loud (annoying)",
        "car alarm",
        "galvanized",
        "discount",
        "'dog that slaps you'",
        "boogie board",
        "real OG",
        "shunned and exiled",
        "cult classic",
        "ridge racer",
        "former iron chef",
        "corn enjoying",
        "smoke-engulfed",
        "sleek and clean",
        "potato pie",
        "NASTY FREAK",
        "blessed and/or damned",
        ".  .  .  . ",
        "wide (in mindset)",
        "docile, yet dangerous",
        "long haul",
        "saucy",
        "down to earth",
        "down to mars",
        "wobbly",
        "gambling",
        "charming",
        "bird with a memory, the memory is in the",
        "locked in",
        "locked out?",
        "Dad approved",
        "table-to-farm",
        "revolutionary",
        "cube enjoying",
        "wasted potential",
        "zen anarchist",
        "reckless/feckless",
        "mini-crossword solving",
        "melody-indifferent",
        "proudly asexual",
        "closeted spotify subscriber (ugh)",
        "boundary pushing",
        "stumbling and iterating",
        "sicko freak",
        "'for the boys :('",
        "short-memory, long",
        "hammers only",
        "drunken memory",
        "new dad",
        "step uncle",
        "pepperoni",
        "genoa salami",
        "shin megami tensei",
        "free palestine",
        "neo-luddite",
        "capitalist bootlicker",
        "simply unwavering",
        "real stanky lil fella, not allowed on planes etc., more durian than a",
        "< SENT TO ANTARCTICA FOR FORCED LABOR :) >",
        "high-priced import",
        "small bird model AI slop garbage",
        "jazz quartet",
        "prison abolitionist",
        "wallpaper taste-tester",
        "no longer endangered ( thanks to you ;) )",
        "wet",
        "avant-garde",
    ];
    let chosen_word = *sources.choose(&mut rng).unwrap();
    chosen_word.to_string()
}
